export const FALLBACK_TOURS = [
  { _id: 't1', title: '5-Day Maasai Mara Safari — Big Five Guaranteed', slug: 'maasai-mara-big-five-5day', category: 'safari', destination: 'Maasai Mara', country: 'kenya', images: ['https://images.unsplash.com/photo-1547970810-dc1eac37d174?w=600'], price: 480, duration: '5 days', groupSize: 8, rating: 4.9, reviewCount: 312, operator: 'Mara Safaris', verified: true, instantBooking: true, description: 'Experience the ultimate Big Five safari in the world-famous Maasai Mara with expert guides and luxury tented camps.', includes: ['Park fees', 'All meals', 'Game drives', 'Airport transfers'], highlights: ['Big Five sightings', 'Sunset game drives', 'Bush breakfast'] },
  { _id: 't2', title: 'Zanzibar Dhow Cruise & Spice Tour', slug: 'zanzibar-dhow-cruise-spice', category: 'beach', destination: 'Zanzibar', country: 'tanzania', images: ['https://images.unsplash.com/photo-1516426122078-c23e76319801?w=600'], price: 75, duration: '1 day', groupSize: 12, rating: 4.8, reviewCount: 197, operator: 'Zanzibar Xplore', verified: true, instantBooking: true, description: 'Sail on a traditional dhow and explore Zanzibar\'s aromatic spice farms.', includes: ['Dhow cruise', 'Spice tour', 'Lunch'], highlights: ['Stone Town views', 'Spice tasting', 'Snorkeling stop'] },
  { _id: 't3', title: 'Kilimanjaro Summit Trek — 7 Days Machame', slug: 'kilimanjaro-machame-7day', category: 'mountain', destination: 'Kilimanjaro', country: 'tanzania', images: ['https://images.unsplash.com/photo-1621414050345-53db43f7e7ab?w=600'], price: 1850, duration: '7 days', groupSize: 6, rating: 4.9, reviewCount: 88, operator: 'Kili Climbers', verified: true, instantBooking: false, description: 'Summit Africa\'s highest peak via the scenic Machame Route with certified mountain guides.', includes: ['Park fees', 'Camping equipment', 'All meals', 'Porter support'], highlights: ['Uhuru Peak', 'Barranco Wall', 'Alpine desert'] },
  { _id: 't4', title: 'Serengeti Great Migration Safari — Private Vehicle', slug: 'serengeti-migration-private', category: 'safari', destination: 'Serengeti', country: 'tanzania', images: ['https://images.unsplash.com/photo-1534177616072-ef7dc120449d?w=600'], price: 960, duration: '4 days', groupSize: 4, rating: 5.0, reviewCount: 143, operator: 'Tanzania Wild', verified: true, instantBooking: true, description: 'Witness the Great Migration across the endless Serengeti plains.', includes: ['Park fees', '4x4 safari vehicle', 'All meals', 'Lodging'], highlights: ['River crossings', 'Predator action', 'Balloon option'] },
  { _id: 't5', title: 'Nairobi National Park Half-Day Safari', slug: 'nairobi-national-park', category: 'safari', destination: 'Nairobi', country: 'kenya', images: ['https://images.unsplash.com/photo-1547970810-dc1eac37d174?w=600'], price: 95, duration: '4 hours', groupSize: 8, rating: 4.7, reviewCount: 254, operator: 'Nairobi Safaris', verified: true, instantBooking: true, description: 'Wildlife safari minutes from Nairobi city centre.', includes: ['Park fees', 'Game drive', 'Hotel pickup'], highlights: ['Rhinos', 'Lions', 'City skyline backdrop'] },
  { _id: 't6', title: 'Diani Beach Snorkeling & Marine Park', slug: 'diani-snorkeling', category: 'beach', destination: 'Diani', country: 'kenya', images: ['https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=600'], price: 65, duration: '1 day', groupSize: 10, rating: 4.8, reviewCount: 189, operator: 'Diani Dive', verified: false, instantBooking: true, description: 'Explore vibrant coral reefs in Kenya\'s best marine park.', includes: ['Snorkeling gear', 'Boat trip', 'Guide'], highlights: ['Coral gardens', 'Tropical fish', 'White sand beach'] },
  { _id: 't7', title: 'Amboseli Elephant Safari — 3 Days', slug: 'amboseli-elephant-safari', category: 'safari', destination: 'Amboseli', country: 'kenya', images: ['https://images.unsplash.com/photo-1551649001-7a2482d98d05?w=600'], price: 390, duration: '3 days', groupSize: 6, rating: 4.9, reviewCount: 201, operator: 'Kenya Wilds', verified: true, instantBooking: true, description: 'Get up close with Amboseli\'s famous elephant herds beneath Kilimanjaro.', includes: ['Park fees', 'Lodging', 'All meals', 'Game drives'], highlights: ['Elephant herds', 'Kilimanjaro views', 'Bird watching'] },
  { _id: 't8', title: 'Maasai Cultural Village Experience', slug: 'maasai-cultural', category: 'cultural', destination: 'Maasai Mara', country: 'kenya', images: ['https://images.unsplash.com/photo-1547970810-dc1eac37d174?w=600'], price: 45, duration: '3 hours', groupSize: 15, rating: 4.7, reviewCount: 203, operator: 'Mara Safaris', verified: true, instantBooking: true, description: 'Immerse yourself in authentic Maasai culture and traditions.', includes: ['Village visit', 'Traditional dance', 'Local guide'], highlights: ['Warrior dance', 'Beadwork demo', 'Traditional homes'] },
  { _id: 't9', title: 'Ngorongoro Crater Day Trip', slug: 'ngorongoro-crater', category: 'safari', destination: 'Ngorongoro', country: 'tanzania', images: ['https://images.unsplash.com/photo-1540202403-b7abd6747a18?w=600'], price: 280, duration: '1 day', groupSize: 8, rating: 5.0, reviewCount: 167, operator: 'Tanzania Wild', verified: true, instantBooking: true, description: 'Descend into the world\'s largest intact volcanic caldera teeming with wildlife.', includes: ['Crater fees', '4x4 vehicle', 'Picnic lunch'], highlights: ['Black rhino', 'Flamingos', 'Crater floor'] },
  { _id: 't10', title: 'Lamu Old Town Cultural Walk', slug: 'lamu-old-town', category: 'cultural', destination: 'Lamu', country: 'kenya', images: ['https://images.unsplash.com/photo-1609198092458-38a293c7ac4b?w=600'], price: 35, duration: '2 hours', groupSize: 12, rating: 4.8, reviewCount: 92, operator: 'Lamu Heritage', verified: false, instantBooking: true, description: 'Explore the UNESCO-listed Swahili architecture of Lamu Old Town.', includes: ['Local guide', 'Historical sites'], highlights: ['Swahili houses', 'Donkey alleys', 'Waterfront views'] },
  { _id: 't11', title: 'Maasai Mara Balloon Safari at Sunrise', slug: 'mara-balloon', category: 'adventure', destination: 'Maasai Mara', country: 'kenya', images: ['https://images.unsplash.com/photo-1547970810-dc1eac37d174?w=600'], price: 320, duration: '4 hours', groupSize: 8, rating: 5.0, reviewCount: 87, operator: 'Air Kenya Balloons', verified: true, instantBooking: false, description: 'Float above the Mara at dawn with champagne breakfast.', includes: ['Balloon flight', 'Champagne breakfast', 'Certificate'], highlights: ['Sunrise views', 'Wildlife from above', 'Bush breakfast'] },
  { _id: 't12', title: 'Naivasha Boat Safari & Crescent Island', slug: 'naivasha-boat', category: 'adventure', destination: 'Naivasha', country: 'kenya', images: ['https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=600'], price: 55, duration: '1 day', groupSize: 10, rating: 4.6, reviewCount: 134, operator: 'Rift Valley Tours', verified: true, instantBooking: true, description: 'Boat across Lake Naivasha and walk among giraffes on Crescent Island.', includes: ['Boat ride', 'Island walk', 'Guide'], highlights: ['Hippos', 'Giraffes', 'Birdlife'] },
]

export const FALLBACK_DESTINATIONS = [
  { _id: '1', name: 'Maasai Mara', slug: 'maasai-mara', country: 'kenya', heroImage: 'https://images.unsplash.com/photo-1547970810-dc1eac37d174?w=600', rating: 4.9, reviewCount: 1240, tourCount: 86, tags: ['Wildlife', 'Safari'], description: 'Home of the Great Wildebeest Migration and Africa\'s finest Big Five wildlife viewing.', bestTimeToVisit: 'July–October', travelTips: 'Book safari lodges early during migration season.' },
  { _id: '2', name: 'Zanzibar', slug: 'zanzibar', country: 'tanzania', heroImage: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=600', rating: 4.8, reviewCount: 890, tourCount: 54, tags: ['Beach', 'Culture'], description: 'Pristine beaches and Swahili culture on the Spice Island.', bestTimeToVisit: 'June–October', travelTips: 'Respect local customs in Stone Town.' },
  { _id: '3', name: 'Kilimanjaro', slug: 'kilimanjaro', country: 'tanzania', heroImage: 'https://images.unsplash.com/photo-1621414050345-53db43f7e7ab?w=600', rating: 4.9, reviewCount: 620, tourCount: 32, tags: ['Trekking', 'Mountain'], description: "Africa's highest peak at 5,895m — a bucket-list climb.", bestTimeToVisit: 'January–March, June–October', travelTips: 'Allow time for acclimatization.' },
  { _id: '4', name: 'Serengeti', slug: 'serengeti', country: 'tanzania', heroImage: 'https://images.unsplash.com/photo-1534177616072-ef7dc120449d?w=600', rating: 5.0, reviewCount: 1100, tourCount: 98, tags: ['Wildlife', 'Safari'], description: 'Endless plains and year-round wildlife including the Great Migration.', bestTimeToVisit: 'Year-round', travelTips: 'Migration timing varies — check with your operator.' },
  { _id: '5', name: 'Mombasa', slug: 'mombasa', country: 'kenya', heroImage: 'https://images.unsplash.com/photo-1523805009345-7448845a9e53?w=600', rating: 4.7, reviewCount: 980, tourCount: 71, tags: ['Beach', 'History'], description: "Kenya's vibrant coastal city with rich Swahili heritage.", bestTimeToVisit: 'December–March', travelTips: 'Visit Fort Jesus and Old Town.' },
  { _id: '6', name: 'Diani Beach', slug: 'diani-beach', country: 'kenya', heroImage: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=600', rating: 4.8, reviewCount: 560, tourCount: 38, tags: ['Beach', 'Snorkeling'], description: "Kenya's most celebrated beach with turquoise waters.", bestTimeToVisit: 'December–March', travelTips: 'Try the marine park snorkeling trips.' },
  { _id: '7', name: 'Ngorongoro', slug: 'ngorongoro', country: 'tanzania', heroImage: 'https://images.unsplash.com/photo-1540202403-b7abd6747a18?w=600', rating: 4.9, reviewCount: 742, tourCount: 45, tags: ['Wildlife', 'Crater'], description: "World's largest intact volcanic caldera with incredible wildlife density.", bestTimeToVisit: 'Year-round', travelTips: 'Start early to avoid crowds in the crater.' },
  { _id: '8', name: 'Lamu', slug: 'lamu', country: 'kenya', heroImage: 'https://images.unsplash.com/photo-1609198092458-38a293c7ac4b?w=600', rating: 4.8, reviewCount: 320, tourCount: 28, tags: ['Culture', 'History'], description: 'Ancient Swahili town and UNESCO World Heritage site.', bestTimeToVisit: 'July–March', travelTips: 'No cars on the island — enjoy the slow pace.' },
  { _id: '9', name: 'Amboseli', slug: 'amboseli', country: 'kenya', heroImage: 'https://images.unsplash.com/photo-1551649001-7a2482d98d05?w=600', rating: 4.8, reviewCount: 410, tourCount: 34, tags: ['Wildlife', 'Elephants'], description: 'Elephants with Kilimanjaro backdrop — iconic African scenery.', bestTimeToVisit: 'June–October', travelTips: 'Morning light is best for Kilimanjaro photos.' },
  { _id: '10', name: 'Arusha', slug: 'arusha', country: 'tanzania', heroImage: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=600', rating: 4.6, reviewCount: 280, tourCount: 52, tags: ['Gateway', 'Culture'], description: "Tanzania's safari gateway city at the foot of Mount Meru.", bestTimeToVisit: 'Year-round', travelTips: 'Great base for northern circuit safaris.' },
  { _id: '11', name: 'Naivasha', slug: 'naivasha', country: 'kenya', heroImage: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=600', rating: 4.7, reviewCount: 380, tourCount: 29, tags: ['Lake', 'Nature'], description: 'Flamingos and hippos on the Great Rift Valley lake.', bestTimeToVisit: 'Year-round', travelTips: 'Combine with Hell\'s Gate National Park.' },
  { _id: '12', name: 'Dar es Salaam', slug: 'dar-es-salaam', country: 'tanzania', heroImage: 'https://images.unsplash.com/photo-1530521954074-e64f6810b32d?w=600', rating: 4.5, reviewCount: 195, tourCount: 18, tags: ['City', 'Coastal'], description: "Tanzania's largest and most cosmopolitan city.", bestTimeToVisit: 'June–October', travelTips: 'Ferry to Zanzibar departs from here.' },
]

export const FALLBACK_GUIDES = [
  { _id: 'g1', name: 'Joseph Kamau', category: 'safari', languages: ['English', 'Swahili', 'French'], rating: 5.0, reviewCount: 128, dailyRate: 80, experience: 12, verified: true, avatar: null, color: '#1B4332', initials: 'JK', specializations: ['Big Five tracking', 'Bird watching', 'Photography'], bio: 'KWS-certified guide with 12 years in Maasai Mara. Specialist in big cat behaviour.' },
  { _id: 'g2', name: 'Amina Mohamed', category: 'cultural', languages: ['English', 'Swahili', 'Arabic'], rating: 4.9, reviewCount: 95, dailyRate: 60, experience: 8, verified: true, avatar: null, color: '#185FA5', initials: 'AM', specializations: ['Stone Town', 'Spice tours', 'Coastal cuisine'], bio: 'Cultural guide with 8 years exploring Zanzibar\'s history and Swahili heritage.' },
  { _id: 'g3', name: 'Charles Mwangi', category: 'mountain', languages: ['English', 'Swahili'], rating: 4.9, reviewCount: 72, dailyRate: 120, experience: 15, verified: true, avatar: null, color: '#7B341E', initials: 'CM', specializations: ['Kilimanjaro', 'Mount Kenya', 'Wilderness first aid'], bio: 'KPAP-certified mountain guide. 15 years summiting Kilimanjaro and Mount Kenya.' },
  { _id: 'g4', name: 'Fatuma Ngugi', category: 'photography', languages: ['English', 'Swahili', 'German'], rating: 4.8, reviewCount: 54, dailyRate: 95, experience: 6, verified: false, avatar: null, color: '#5C2D91', initials: 'FN', specializations: ['Wildlife photography', 'Sunrise shoots', 'Portrait sessions'], bio: 'Photography guide specialising in golden hour wildlife shoots across the Mara.' },
  { _id: 'g5', name: 'Daniel Oloo', category: 'city', languages: ['English', 'Swahili', 'Luo'], rating: 4.7, reviewCount: 88, dailyRate: 45, experience: 5, verified: true, avatar: null, color: '#0B5394', initials: 'DO', specializations: ['Nairobi food tours', 'Street art', 'Nightlife'], bio: 'Nairobi city guide with intimate knowledge of hidden gems and local culture.' },
  { _id: 'g6', name: 'Grace Mutua', category: 'safari', languages: ['English', 'Swahili', 'Kikuyu'], rating: 4.8, reviewCount: 63, dailyRate: 75, experience: 9, verified: true, avatar: null, color: '#2D6A4F', initials: 'GM', specializations: ['Amboseli elephants', 'Night drives', 'Bush walks'], bio: 'Passionate about Amboseli\'s elephant families and Kilimanjaro views.' },
]

export const FALLBACK_STAYS = [
  { _id: 's1', name: 'Mara Serena Safari Lodge', type: 'lodge', slug: 'mara-serena-safari-lodge', destination: 'Maasai Mara', pricePerNight: 320, currency: 'USD', rating: 4.9, reviewCount: 420, images: ['https://images.unsplash.com/photo-1547970810-dc1eac37d174?w=600'], amenities: ['Pool', 'Spa', 'WiFi', 'Restaurant'], description: 'Luxury lodge perched on a hilltop overlooking the Maasai Mara plains.' },
  { _id: 's2', name: 'Zanzibar Beach Resort', type: 'resort', slug: 'zanzibar-beach-resort', destination: 'Zanzibar', pricePerNight: 180, currency: 'USD', rating: 4.8, reviewCount: 310, images: ['https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600'], amenities: ['Beachfront', 'Pool', 'Spa', 'Snorkeling'], description: 'Beachfront resort with infinity pool and direct access to pristine white sand.' },
  { _id: 's3', name: 'Nairobi City Boutique Hotel', type: 'hotel', slug: 'nairobi-city-boutique', destination: 'Nairobi', pricePerNight: 95, currency: 'USD', rating: 4.7, reviewCount: 280, images: ['https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=600'], amenities: ['WiFi', 'Gym', 'Restaurant', 'Bar'], description: 'Stylish boutique hotel in the heart of Nairobi with rooftop dining.' },
  { _id: 's4', name: 'Serengeti Tented Camp', type: 'lodge', slug: 'serengeti-tented-camp', destination: 'Serengeti', pricePerNight: 450, currency: 'USD', rating: 4.9, reviewCount: 198, images: ['https://images.unsplash.com/photo-1534177616072-ef7dc120449d?w=600'], amenities: ['Safari drives', 'Bush dining', 'Solar power', 'En-suite'], description: 'Intimate tented camp in the heart of the Serengeti migration corridor.' },
  { _id: 's5', name: 'Diani Beach Villa', type: 'villa', slug: 'diani-beach-villa', destination: 'Diani', pricePerNight: 220, currency: 'USD', rating: 4.8, reviewCount: 156, images: ['https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=600'], amenities: ['Private pool', 'Beach access', 'Chef', 'WiFi'], description: 'Private beachfront villa perfect for families and groups.' },
  { _id: 's6', name: 'Amboseli Serena Lodge', type: 'lodge', slug: 'amboseli-serena-lodge', destination: 'Amboseli', pricePerNight: 280, currency: 'USD', rating: 4.8, reviewCount: 234, images: ['https://images.unsplash.com/photo-1551649001-7a2482d98d05?w=600'], amenities: ['Kilimanjaro views', 'Pool', 'Restaurant', 'Game drives'], description: 'Stunning lodge with uninterrupted views of Mount Kilimanjaro.' },
]

export const FALLBACK_TRANSPORT = [
  { _id: 'tr1', name: 'Nairobi → Maasai Mara Shuttle', type: 'bus', slug: 'nairobi-mara-shuttle', route: 'Nairobi - Maasai Mara', price: 45, duration: '5 hours', rating: 4.6, reviewCount: 89, description: 'Daily comfortable shuttle service to Maasai Mara gates.', image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=600' },
  { _id: 'tr2', name: 'Safari Land Cruiser Rental', type: 'car', slug: 'safari-land-cruiser', route: 'Kenya & Tanzania', price: 120, duration: 'Per day', rating: 4.8, reviewCount: 156, description: '4x4 Toyota Land Cruiser with pop-up roof for self-drive safaris.', image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=600' },
  { _id: 'tr3', name: 'Wilson → Mara Charter Flight', type: 'flight', slug: 'wilson-mara-flight', route: 'Nairobi Wilson - Maasai Mara', price: 280, duration: '45 min', rating: 4.9, reviewCount: 67, description: 'Scenic charter flight saving hours of road travel.', image: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=600' },
  { _id: 'tr4', name: 'Dar es Salaam → Zanzibar Ferry', type: 'ferry', slug: 'dar-zanzibar-ferry', route: 'Dar es Salaam - Zanzibar', price: 35, duration: '2 hours', rating: 4.5, reviewCount: 312, description: 'Fast ferry crossing to Zanzibar Island.', image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600' },
  { _id: 'tr5', name: 'Arusha → Serengeti Transfer', type: 'bus', slug: 'arusha-serengeti-transfer', route: 'Arusha - Serengeti', price: 55, duration: '6 hours', rating: 4.7, reviewCount: 94, description: 'Direct transfer to Serengeti national park entrance.', image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=600' },
  { _id: 'tr6', name: 'Mombasa Airport Transfer', type: 'car', slug: 'mombasa-airport-transfer', route: 'Moi Airport - Mombasa/Diani', price: 40, duration: '1-2 hours', rating: 4.6, reviewCount: 203, description: 'Private airport pickup to Mombasa city or Diani Beach.', image: 'https://images.unsplash.com/photo-1449965405229-13993e5750de?w=600' },
]

export function findTourBySlug(slug: string) {
  const exactMatch = FALLBACK_TOURS.find(t => t.slug === slug)
  if (exactMatch) return exactMatch

  const normalizedSlug = slug.replace(/-\d+$/, '')
  return FALLBACK_TOURS.find(t =>
    t.slug === normalizedSlug ||
    slug.startsWith(`${t.slug}-`) ||
    normalizedSlug.startsWith(`${t.slug}-`) ||
    t.slug.startsWith(`${normalizedSlug}-`)
  )
}

export function findDestinationBySlug(slug: string) {
  return FALLBACK_DESTINATIONS.find(d => d.slug === slug)
}

export function findGuideById(id: string) {
  return FALLBACK_GUIDES.find(g => g._id === id)
}

export function findStayBySlug(slug: string) {
  return FALLBACK_STAYS.find(s => s.slug === slug)
}
