export const BLOG_POSTS = [
  {
    slug: 'great-migration-guide',
    title: 'Ultimate Guide to the Great Migration',
    excerpt: 'Everything you need to know about witnessing the wildebeest migration in the Maasai Mara and Serengeti.',
    metaDescription: 'Plan the perfect Great Migration safari in Kenya and Tanzania with seasonal timing, best routes, wildlife photography tips, and practical planning advice.',
    keywords: ['Great Migration Kenya', 'Maasai Mara safari', 'Serengeti migration'],
    date: '2026-03-15',
    category: 'Safari',
    content: [
      'The Great Migration is one of the most spectacular wildlife events on Earth, drawing travellers to Kenya and Tanzania each year for the chance to witness thousands of wildebeest and zebra moving across vast grasslands.',
      'The best time to see the migration depends on where you focus your safari. Many travellers plan around the dramatic river crossings in the Maasai Mara while others prefer the wide-open plains of the Serengeti, where the herds spread over enormous distances and predators follow closely behind.',
      'A memorable safari usually combines early morning game drives with relaxed downtime at camp, giving you enough energy for photography and wildlife spotting without feeling rushed. Staying near migration corridors or choosing a lodge with flexible game drive access can make a huge difference to the experience.',
      'For a smoother trip, work with experienced guides who understand seasonal movement patterns, road conditions, and where the herds are most likely to gather. This is especially important if you are travelling during peak season when camps and vehicles book up quickly.',
      'Whether you are planning a first-time Kenya safari or returning for a second adventure, the Great Migration is best enjoyed with patience, flexibility, and a little planning around the weather and movement of the animals.',
      'Book with Tembea Africa to unlock local expertise, flexible guides, and the best access to migration hotspots across the Maasai Mara and Serengeti.',
    ],
    highlights: ['Best months: July to October', 'Ideal base: Maasai Mara or Serengeti', 'Stay flexible for river crossings'],
  },
  {
    slug: 'zanzibar-travel-tips',
    title: '10 Things to Know Before Visiting Zanzibar',
    excerpt: 'From spice tours to beach etiquette — your essential Zanzibar travel guide.',
    metaDescription: 'Get ready for Zanzibar with essential island travel tips on beaches, Stone Town culture, spice farms, transport, and local etiquette for a smoother island holiday.',
    keywords: ['Zanzibar travel tips', 'Zanzibar beach holiday', 'Stone Town guide'],
    date: '2026-02-28',
    category: 'Beach',
    content: [
      'Zanzibar is a wonderful mix of laid-back beaches, rich history, and flavourful cuisine, making it a strong choice for couples, families, and travellers looking for a slower island escape.',
      'The island is best enjoyed by combining city time in Stone Town with beach time on the east coast and one or two day trips to spice farms, marine parks, or secluded coves. This balance helps you experience both the culture and the coastline without rushing.',
      'Packing lightly is a smart move because ferries, taxis, and small island roads can be less predictable than expected. A light cover-up, reef-safe sunscreen, and good walking shoes will make your days more comfortable.',
      'Respecting local culture also matters. When you visit villages, religious sites, or local markets, it is polite to dress modestly and ask before taking photos of people or homes.',
      'For the smoothest trip, book transfers in advance during busy holiday periods and build in time for weather delays, especially if you plan to hop between islands or join boat excursions.',
      'Choose Tembea Africa for trusted local guidance, secure transfers, and Zanzibar experiences that blend beach time, culture, and authentic Swahili flavour.',
    ],
    highlights: ['Perfect for 3–5 day trips', 'Great for snorkeling and spice tours', 'Cooler evenings in Stone Town'],
  },
  {
    slug: 'kilimanjaro-preparation',
    title: 'How to Prepare for Kilimanjaro',
    excerpt: 'Training, gear, and altitude tips for a successful summit attempt.',
    metaDescription: 'Learn how to prepare for Kilimanjaro with proven training methods, gear packing tips, acclimatization strategies, and route planning for a successful summit.',
    keywords: ['Kilimanjaro preparation', 'climbing Kilimanjaro', 'altitude tips'],
    date: '2026-02-10',
    category: 'Adventure',
    content: [
      'Climbing Kilimanjaro is a memorable achievement, but it requires both physical preparation and a realistic mindset. The mountain rewards travellers who train steadily rather than trying to cram all their fitness work into the final weeks.',
      'A good preparation plan includes uphill walking, stair climbing, and long endurance sessions so your body can handle the daily rhythm of climbing. It also helps to rehearse with a backpack so you know how your gear feels on the trail.',
      'Layered clothing is essential because the mountain can be warm during the day and freezing at night. A waterproof jacket, warm sleeping layers, and proper hiking boots will make the summit push far more comfortable.',
      'Acclimatization is just as important as fitness. Choosing a longer route gives your body more time to adjust to the altitude and can improve your chances of reaching the top without feeling overly exhausted.',
      'The best Kilimanjaro adventures are built around patience, pacing, and listening to your guide. Slow and steady often wins the summit, especially when the weather changes quickly and the trail becomes challenging.',
      'Work with Tembea Africa to choose the right route, stay safe on the trail, and get local support from experienced mountain guides.',
    ],
    highlights: ['Train with uphill hikes', 'Pack layered clothing', 'Choose a slower route when possible'],
  },
  {
    slug: 'kenya-safari-budget',
    title: 'Kenya Safari on a Budget',
    excerpt: 'Affordable ways to experience world-class wildlife without breaking the bank.',
    metaDescription: 'Discover how to enjoy a Kenya safari on a budget with smart timing, shared tours, mid-range lodges, and practical cost-saving tips.',
    keywords: ['Kenya safari budget', 'affordable safari Kenya', 'budget safari tips'],
    date: '2026-01-22',
    category: 'Safari',
    content: [
      'A safari in Kenya can be more affordable than many travellers expect when you choose the right season, transport, and accommodation. The key is to balance wildlife quality with a realistic budget instead of trying to do everything at once.',
      'Shared vehicles, group safaris, and mid-range camps are often the best value for travellers who still want high-quality game viewing. These options can offer excellent access to parks without the cost of private lodges.',
      'Traveling during shoulder season can also bring better prices and fewer crowds, especially in popular parks such as the Maasai Mara and Amboseli. You can still enjoy impressive wildlife sightings while avoiding the highest peak-season rates.',
      'Another smart strategy is to pair a shorter safari with a few nights in Nairobi or a nearby town, allowing you to spread out your time and reduce the pressure to book expensive park packages all at once.',
      'With a little planning, a budget safari in Kenya can still deliver unforgettable wildlife moments, comfortable stays, and a genuine sense of adventure.',
      'Let Tembea Africa help you build a budget-friendly itinerary that still includes iconic wildlife, reliable transfers, and local safari knowledge.',
    ],
    highlights: ['Consider shared vehicles', 'Choose shoulder season dates', 'Book park entry and transfers early'],
  },
]
